// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulrhljhdcgbzcifhcwzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVscmhsamhkY2diemNpZmhjd3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MDkxOTcsImV4cCI6MjA1OTQ4NTE5N30.3zP95giN8p4DQ1Qeq1qGqV7Ot4ovbI5pxxVB01sgN_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);